# Cuman buat tes prometheus scrapenya bener gk
global:
  scrape_interval: 15s  # How often Prometheus scrapes data

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'django'
    static_configs:
      - targets: ['host.docker.internal:8001', 'host.docker.internal:8002']  # Change if Django is running on a different host
  