name: Run Tests

on:
  push:
    branches: [ main, master ]
    paths-ignore:
        - '**.md'
  pull_request:
    branches: [ main, master ]
    paths-ignore:
        - '**.md'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python3
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Get Dependencies
      run: pip install -r requirements.txt

    - name: Run Tests
      run: chmod +x ./manage.py && ./manage.py test